# Generated by Django 3.0.3 on 2020-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coches', '0002_auto_20200623_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coches',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='coches',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='coches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web_personal/projects/renta_coches',
                                    verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='coches',
            name='nombre',
            field=models.ImageField(blank=True, default=None, max_length=50, null=True, upload_to=''),
        ),
    ]
