# Generated by Django 3.0.3 on 2020-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default=None, max_length=50)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50)),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
