# Generated by Django 3.0.3 on 2020-06-23 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rutas', '0004_auto_20200623_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
    ]
