# Generated by Django 3.0.3 on 2020-06-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('conductores', '0002_auto_20200623_1318'),
        ('pasajero', '0002_auto_20200623_1255'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='boleto',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='conductores.Conductor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pasajero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajero.Pasajero'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
