# Generated by Django 3.0.3 on 2020-06-23 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reserva', '0003_auto_20200623_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
