# Generated by Django 3.0.3 on 2020-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='correo',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='direccion',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
