# Generated by Django 3.0.3 on 2020-06-23 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('conductores', '0002_auto_20200623_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
