# Generated by Django 3.0.3 on 2020-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conductores', '0003_auto_20200623_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AddField(
            model_name='conductor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='projects/renta_coches/conductores/',
                                    verbose_name='Imagen'),
        ),
    ]
