# Generated by Django 3.0.3 on 2020-06-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasajero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='direccion',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
