# Generated by Django 3.0.3 on 2020-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pasajero', '0003_auto_20200623_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasajero',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AddField(
            model_name='pasajero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='projects/renta_coches/pasajeros',
                                    verbose_name='Imagen'),
        ),
    ]
