# Generated by Django 3.0.3 on 2020-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Descripcion')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='Link')),
                ('image',
                 models.ImageField(blank=True, null=True, upload_to='web_personal/projects', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('domain', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('career', models.CharField(blank=True, max_length=50, verbose_name='Carrera')),
                ('year', models.DateField(auto_now_add=True, verbose_name='Año')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripcion')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('fee', models.CharField(blank=True, max_length=50, verbose_name='Honorarios')),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
