# Generated by Django 3.0.3 on 2020-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web_personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Projects',
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
