# Generated by Django 3.0.3 on 2020-06-11 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web_personal', '0002_auto_20200611_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
