# Generated by Django 3.0.3 on 2020-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_personal', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='skills',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
