# Generated by Django 3.0.3 on 2020-07-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('web_personal', '0003_remove_projects_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_personal.User'),
        ),
        migrations.AddField(
            model_name='skills',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_personal.User'),
        ),
    ]
