# Generated by Django 3.0.3 on 2020-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_personal', '0004_auto_20200611_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='color',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='link',
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='domain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
